update ci
sofa-framework/ManifoldTopologies pull request #10
Opened 2024-09-12 15:10 UTC by antennae

https://github.com/sofa-framework/sofa/discussions/4979

2024-09-12 15:18 UTC, alxbilger approved these changes

2024-09-12 15:19 UTC, alxbilger commented
@sofa-framework/consortium-staff Need an approval here

2024-09-13 09:28 UTC, epernod requested changes
forgot this one:
https://github.com/sofa-framework/ManifoldTopologies/blob/5770aeb4ffeb9c811ac786f4665f12c5182624af/.github/workflows/ci.yml#L104

2024-09-16 07:53 UTC, epernod approved these changes

2024-09-16 07:54 UTC, merged